initial_screen = "library"
hide_display_name = true
notify = true
use_nerdfont = true
repeat = "playlist"
library_tabs = [
  "playlists"
]

[theme]
background = "#1a1b26"
primary = "#4fd6be"
secondary = "#b4c4f6"
title = "#ff9e64"
playing = "#ff9e64"
playing_selected = "#bb9af7"
playing_bg = "#1a1b2b"
highlight = "#7aa2f7"
highlight_bg = "#1a1b26"
error = "#414868"
error_bg = "#f7768e"
statusbar = "#ff9e64"
statusbar_progress = "#7aa2f7"
statusbar_bg = "#1a1b26"
cmdline = "#44d6be"
cmdline_bg = "#24283b"
search_match = "#f7768e"

[track_format]
left = "%artists - %title"
center = "%album"
right = "%duration"

[notification_format]
title = "%title"
body = "%artists"
