initial_screen = "library"
use_nerdfont = true
repeat = "playlist"
library_tabs = [
  "playlists"
]


[theme]
background = "#000000"
primary = "#F5F5F5"
secondary = "#DCDCDC"
title = "#F5F5F5"
playing = "#EFC11A"
playing_selected = "#EFC11A"
playing_bg = "#1E1E1E"
highlight = "#73DACA"
highlight_bg = "#000000"
error = "#1E1E1E"
error_bg = "#F97E72"
statusbar = "#000000"
statusbar_progress = "#F5F5F5"
statusbar_bg = "#DCDCDC"
cmdline = "#F5F5F5"
cmdline_bg = "#222222"

