# Default colors
[colors.primary]
background = '#313440'
foreground = '#fafafa'

dim_foreground    = '#dbdbdb'
bright_foreground = '#ffffff'

# Cursor colors
[colors.cursor]
text   = '#252834'
cursor = '#f4d1ff'

# Normal colors
[colors.normal]
black = '#282C34'
red = '#ff6059'
green = '#5fff87'
yellow = '#ffff87'
blue = '#5fafff'
magenta = '#af87ff'
cyan = '#5fafff'
white = '#fafafa'

# Bright colors
[colors.bright]
black = '#333942'
red = '#ff6a63'
green = '#6aff92'
yellow = '#ffff92'
blue = '#6abaff'
magenta = '#b892ff'
cyan = '#6abaff'
white = '#ffffff'

# Dim colors
[colors.dim]
black = '#1d242c'
red = '#d14d4f'
green = '#4fd975'
yellow = '#d9d975'
blue = '#4f97d9'
magenta = '#936fd9'
cyan = '#4f97d9'
white = '#d9d9d9'
