-- load my various configuration files
require("plugins")
require("providers")
require("lsp")
require("saga")
require("trees")
require("gaze")
require("format")
require("utils")
require("prettys")
require("theme")
require("projects")
require("vcs")
require("neovide")
require("fonts")
