-- set the comment font to Delugia in italic
-- vim.cmd("hi Comment font='Delugia_PL_Mono_Regular_Italic 13'")
-- vim.cmd("hi Keyword font='Delugia_PL_Mono_Regular_Italic 13'")
-- vim.cmd("hi Italic font='Delugia_PL_Mono_Regular_Italic 13'")
