#!/bin/zsh

show=10
font="Manrope Semi-Bold"
font_size=20
(( line_height=$font_size * 2.25 ))
prompt=""
background="#261447f2"
foreground="#fffbfcf2"
highlight_background="#261447f2"
highlight_foreground="#ff3864f2"
title_color="#5af78ef2"

bemenu --width-factor 0.75 \
       --margin 100 \
       --grab \
       --no-overlap \
       --ignorecase \
       --no-cursor \
       --line-height $line_height \
       --list $show \
       --prompt $prompt \
       --ab $background \
       --af $foreground \
       --sb $background \
       --sf $foreground \
       --fbb $background \
       --fbf $foreground \
       --tb $background \
       --tf $title_color \
       --fb $background \
       --ff $foreground \
       --cb $background \
       --cf $background \
       --nb $background \
       --nf $foreground \
       --hb $highlight_background \
       --hf $highlight_foreground \
       --fn "$font $font_size"
