#!/bin/zsh

show=10
font="JetBrainsMono NF Medium"
font_size=18
(( line_height=$font_size * 2 ))
prompt=">"
background="#2d3f76"
foreground="#c8d3f5"
highlight_background=$background
highlight_foreground="#4fd6b3"

bemenu --no-overlap \
       --ignorecase \
       --no-cursor \
       --line-height $line_height \
       --list $show \
       --prompt $prompt \
       --ab $background \
       --af $foreground \
       --sb $background \
       --sf $foreground \
       --fbb $background \
       --fbf $foreground \
       --tb $background \
       --tf $foreground \
       --fb $background \
       --ff $foreground \
       --cb $background \
       --cf $background \
       --nb $background \
       --nf $foreground \
       --hb $highlight_background \
       --hf $highlight_foreground \
       --fn "$font $font_size"
